name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: gcloud --version

  unit:
    name: bats test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # TODO(jthegedus): use cache action on asdf
      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1
      # - name: Download asdf core test/banned_commands.bats
      #   run: |
      #     curl https://raw.githubusercontent.com/asdf-vm/asdf/master/test/banned_commands.bats -o ./test/banned_commands.bats
      #     curl https://raw.githubusercontent.com/asdf-vm/asdf/master/test/test_helpers.bash -o ./test/test_helpers.bash
      - name: Run Bats tests
        run: bats test
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
