name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: gcloud --version

  unit:
    name: bats test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1
      - name: Cache asdf
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-
      - name: Install dependencies in .tool-versions
        uses: asdf-vm/actions/install@v1

      # - name: Download asdf core test/banned_commands.bats
      #   run: |
      #     curl https://raw.githubusercontent.com/asdf-vm/asdf/master/test/banned_commands.bats -o ./test/banned_commands.bats
      #     curl https://raw.githubusercontent.com/asdf-vm/asdf/master/test/test_helpers.bash -o ./test/test_helpers.bash
      - name: Run Bats tests
        run: bats test
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
